#!/bin/sh /etc/rc.common
# shellcheck disable=SC3043,SC3003,SC2019,SC2018,SC3020,SC3057

START=50
USE_PROCD=1
DEBUG=1

# Dynamic content
DEBUG_FILE="/tmp/dscpclassify.debug"
INCLUDES_PATH="/tmp/etc/dscpclassify.d"
PRE_INCLUDE="${INCLUDES_PATH}/pre-include.nft"
POST_INCLUDE="${INCLUDES_PATH}/post-include.nft"

# Static content
MAIN="/etc/dscpclassify.d/main.nft"
VERDICTS="/etc/dscpclassify.d/verdicts.nft"
MAPS="/etc/dscpclassify.d/maps.nft"


log() {
	local level="$1" message="$2"
	logger -t dscpclassify -p "daemon.${level}" "$message"
	case "$level" in
	info | warning | err) >&2 echo "$message" ;;
	esac
}

create_debug_file() {
	{
		echo "dscpclassify${action:+ $action}: $(date)"
		echo $'\n'"<--- ${PRE_INCLUDE} --->"
		[ -f "$PRE_INCLUDE" ] && cat "$PRE_INCLUDE"
		echo $'\n'"<--- ${POST_INCLUDE} --->"
		[ -f "$POST_INCLUDE" ] && cat "$POST_INCLUDE"
		echo $'\n'"<--- nft -f ${MAIN} --->"
		echo "${nft_result:+$nft_result}"
		echo $'\n'"<--- nft list table inet dscpclassify --->"
		nft list table inet dscpclassify 2>&1
	} > "$DEBUG_FILE"
}

delete_debug_file() {
	rm -f "$DEBUG_FILE"
}

delete_includes() {
	rm -rf "$INCLUDES_PATH"
}

destroy_table() {
	nft destroy table inet dscpclassify &>/dev/null
}

cleanup_service() {
	destroy_table
	delete_debug_file
	delete_includes
}

cleanup_setup() {
	delete_debug_file
	delete_includes
}

pre_include() {
	echo "$1" >>"$PRE_INCLUDE"
}

post_include() {
	echo "$1" >>"$POST_INCLUDE"
}

config_foreach_reverse() {
	local ___function="$1"
	local ___type="$2"
	shift 2

	for section in $(config_foreach echo "$___type" | sort -r); do
		"$___function" "$section" "$@"
	done
}

# config_get_exclusive_section <variable> <type>
# config_get_exclusive_section <type>
config_get_exclusive_section() {
	local type="${2:-$1}" variable="${2:+$1}"
	local section

	case "${type}${variable}" in
		*[!A-Za-z0-9_]*) return 1 ;;
	esac

	for _section in $(config_foreach echo "$type"); do
		[ -n "$section" ] && {
			log warning "Duplicate ${type} config section ignored"
			break
		}
		section="$_section"
	done

	[ -n "$variable" ] && {
		eval "${variable}=\${section}"
		return 0
	}
	echo "$section"
}

convert_duration_to_seconds() {
	local duration="$1"
	local seconds

	for component in $(echo "$duration" | sed -e 's/\([dhms]\)/\1 /g'); do
		case "$component" in
		*d) seconds=$((seconds + ${component::-1} * 86400)) || return 1 ;;
		*h) seconds=$((seconds + ${component::-1} * 3600)) || return 1 ;;
		*m) seconds=$((seconds + ${component::-1} * 60)) || return 1 ;;
		*s) seconds=$((seconds + ${component::-1})) || return 1 ;;
		*) return 1 ;;
		esac
	done

	echo "$seconds"
}

dscp_class() {
	local class="$1"

	class="$(echo "$class" | tr 'A-Z' 'a-z')"
	case "$class" in
	le) true ;;  # RFC-8622
	be | df) class="cs0" ;;
	cs0 | cs1 | af11 | af12 | af13 | cs2 | af21 | af22 | af23 | cs3 | af31 | af32 | af33 | cs4 | af41 | af42 | af43 | cs5 | va | ef | cs6 | cs7) true ;;
	*) return 1 ;;
	esac

	echo "$class"
}

format_list() {
	local items="$1" delimiter="$2" encapsulator="$3" wrapper="$4"
	local list

	list=$(echo "$items" | tr '\n' ' ' | sed -e "s/^\s*/${encapsulator}/" -e "s/\s*$/${encapsulator}/" -e "s/\s\+/${encapsulator}${delimiter}${encapsulator}/g")
	case ${#wrapper} in
	0) echo "$list" ;;
	2) echo "${wrapper:0:1} ${list} ${wrapper:1:1}" ;;
	*) return 1 ;;
	esac
}

nft_element_list() {
	format_list "$1" ", " "" "{}" 
}

nft_interface_list() {
	format_list "$1" ", " "\"" "{}" 
}

nft_flag_list() {
	format_list "$1" ", "
}

nft_type_list() {
	format_list "$1" " . "
}

fw_zone_interfaces() {
	local interfaces

	interfaces="$(fw4 -q zone "$1" | sort -u)"
	[ -n "$interfaces" ] || return 1
	echo "$interfaces"
}

check_minimum_kernel_release() {
	local minimum_release="$1"
	local current_release current_major current_minor minimum_major minimum_minor

	minimum_major=$(echo "$minimum_release" | awk -F '.' '{print $1}')
	minimum_minor=$(echo "$minimum_release" | awk -F '.' '{print $2}')
	current_release=$(uname -r)
	current_major=$(echo "$current_release" | awk -F '.' '{print $1}')
	current_minor=$(echo "$current_release" | awk -F '.' '{print $2}')
	
	if [ "$current_major" -gt "$minimum_major" ] || { [ "$current_major" = "$minimum_major" ] && [ "$current_minor" -ge "${minimum_minor:-0}" ]; }; then
		return 0
	fi 2>/dev/null
	return 1
}

check_duration() {
	echo "$1" | grep -q -E -e "^([1-9][0-9]*[smhd]){1,4}$"
}

check_family() {
	case "$1" in
	ipv4 | ipv6) return 0 ;;
	esac
	return 1
}

check_port_proto() {
	for i in $1; do
		case "$i" in
		tcp | udp) true ;;
		*) return 1 ;;
		esac
	done
}

check_set_name() {
	case "$1" in
	"")
		log warning "Set is missing the name option"
		return 1
		;;
	bulk_clients | bulk_clients6 | high_throughput_services | high_throughput_services6)
		log warning "Sets cannot overwrite built-in dscpclassify sets"
		return 1
		;;
	bulk_client_detect | bulk_client_detect6 | bulk_client_orig_classify | bulk_client_orig_classify6 | bulk_client_reply_classify | bulk_client_reply_classify6 | high_throughput_service_detect | high_throughput_service_detect6)
		log warning "Sets cannot overwrite built-in dscpclassify meter sets"
		return 1
		;;
	esac
	return 0
}

check_set_size() {
	[ -n "$1" ] || return 0

	if ! [ "$1" -ge 1 ] || ! [ "$1" -le 65535 ]; then
		log warning "Set contains an invalid maxelem option"
		return 1
	fi 2>/dev/null
	return 0
}

check_set_exists() {
	nft -t list set inet dscpclassify "$1" &>/dev/null
}

check_set_against_existing() {
	local name="$1" type="$2" comment="$3" size="$4" flags="$5" timeout="$6"
	local existing_set existing_type

	existing_set=$(nft -t -j list set inet dscpclassify "$name" 2>/dev/null) || return 2

	type="$(echo "$type" | sed 's/\s\+\.\s\+/\n/g')"
	existing_type="$(jsonfilter -s "$existing_set" -e "@.nftables[*].set.type")"
	if [ -n "$existing_type" ]; then
		[ "$existing_type" = "$type" ] || return 1
	else
		existing_type="$(jsonfilter -s "$existing_set" -e "@.nftables[*].set.type[*]")"
		[ "$existing_type" = "$type" ] || return 1
	fi

	[ "$(jsonfilter -s "$existing_set" -e "@.nftables[*].set.comment")" = "$comment" ] || return 1

	[ "$(jsonfilter -s "$existing_set" -e "@.nftables[*].set.size")" = "$size" ] || return 1

	flags="$(echo "$flags" | sed 's/,\s\+/\n/g' | sort)"
	[ "$(jsonfilter -s "$existing_set" -e "@.nftables[*].set.flags[*]" | sort)" = "$flags" ] || return 1

	timeout="$(convert_duration_to_seconds "$timeout")"
	[ "$(jsonfilter -s "$existing_set" -e "@.nftables[*].set.timeout")" = "$timeout" ] || return 1

	return 0
}

check_uint() {
	[ "$1" -ge 0 ] 2>/dev/null
}

parse_rule_ports() {
	for i in $1; do
		echo "$i" | grep -q -E -e "^!?[1-9][0-9]*(-[1-9][0-9]*)?$" || return 1
		case "$i" in
		"!"*) port_negate="$port_negate ${i#*!}" ;;
		*) port="$port $i" ;;
		esac
	done
}

parse_rule_ips() {
	for i in $1; do
		# ipv4 address
		echo "$i" | grep -q -E -e "^!?(([2]([0-4][0-9]|[5][0-5])|[0-1]?[0-9]?[0-9])[.]){3}(([2]([0-4][0-9]|[5][0-5])|[0-1]?[0-9]?[0-9]))(/([0-9]|[12][0-9]|3[0-2]))?$" && {
			case "$i" in
			"!"*) ipv4_negate="$ipv4_negate ${i#*!}" ;;
			*) ipv4="$ipv4 $i" ;;
			esac
			continue
		}

		# ipv6 address
		echo "$i" | grep -q -E -e "^!?(([a-fA-F0-9]{1,4}|):){1,7}([a-fA-F0-9]{1,4}|:)(/[0-9]{1,3})?$" && {
			case "$i" in
			"!"*) ipv6_negate="$ipv6_negate ${i#*!}" ;;
			*) ipv6="$ipv6 $i" ;;
			esac
			continue
		}

		# set name
		echo "$i" | grep -q -E -e "^!?@\w+$" && {
			case "$i" in
			"!"*) ipset_negate="$ipset_negate ${i#*!}" ;;
			*) ipset="$ipset $i" ;;
			esac
			continue
		}

		log warning "Invalid ip/set name: $i"
		return 1
	done
}

parse_set_timeout() {
	[ -n "$timeout" ] || return 0

	[ "$timeout" = 0 ] && {
		flag_timeout=1
		timeout=""
		return 0
	}

	check_uint "$timeout" && {
		flag_timeout=1
		timeout="${timeout}s"
	}

	check_duration "$timeout" || {
		log warning "Set contains an invalid timeout option"
		return 1
	}

	return 0
}

parse_set_flags() {
	[ "$flag_constant" = 1 ] && {
		flags="$flags constant"
	}

	[ "$flag_interval" = 1 ] && {
		flags="$flags interval"
		auto_merge=1
	}

	[ "$flag_timeout" = 1 ] && {
		flags="$flags timeout"
	}

	[ -n "$flags" ] && flags=$(nft_flag_list "$flags")

	return 0
}

parse_set_type() {
	[ -n "$type" ] && return 0

	[ -n "$match" ] || {
		type="${family}_addr"
		return 0
	}

	log warning "The match set option functionality is not yet fully implemented for user sets"

	for i in $match; do
		case "$i" in
		src_* | dest_*) true ;;
		*)
			log warning "Set contains an invalid match option"
			return 1
			;;
		esac

		case "$i" in
		*_ip) type="$type ${family}_addr" ;;
		*_mac) type="$type ether_addr" ;;
		*_port) type="$type inet_service" ;;
		*_net)
			type="$type ${family}_addr"
			flag_interval=1
			;;
		*)
			log warning "Set contains an invalid match option"
			return 1
			;;
		esac
	done
	type=$(nft_type_list "$type")

	return 0
}

create_user_set() {
	local section="$1"
	local comment entry element enabled family flags match size name timeout type
	local flag_constant flag_interval flag_timeout auto_merge
	local error=0

	config_get_bool enabled "$section" enabled 1
	[ "$enabled" = 1 ] || return 0

	config_get comment "$section" comment
	config_get name "$section" name
	config_get family "$section" family ipv4
	config_get match "$section" match
	config_get type "$section" type # allows user to explicity specify the nft set type
	config_get size "$section" maxelem
	config_get timeout "$section" timeout

	config_get_bool flag_constant "$section" constant
	config_get_bool flag_interval "$section" interval

	config_get entry "$section" entry
	config_get element "$section" element # deprecate for naming consistency with fw4 (entry)
	[ -n "$element" ] && log warning "The user set 'element' option is being deprecated in favour of 'entry' for consistency with fw4"

	check_set_name "$name" || error=1
	check_set_size "$size" || error=1
	check_family "$family" || {
		log warning "Set contains an invalid family"
		error=1
	}

	parse_set_type || error=1
	parse_set_timeout || error=1
	parse_set_flags || error=1
	[ "$error" = 0 ] || return 1

	check_set_against_existing "$name" "$type" "$comment" "$size" "$flags" "$timeout" || {
		[ "$?" = 1 ] && post_include "destroy set inet dscpclassify $name"
		post_include "add set inet dscpclassify $name { type $type; ${timeout:+timeout $timeout;} ${size:+size $size;} ${flags:+flags $flags;} ${auto_merge:+auto-merge;} ${comment:+comment \"$comment\";} }"
	}

	[ -n "$entry$element" ] && post_include "add element inet dscpclassify $name $(nft_element_list "$entry $element")"

	return 0
}

rule_l4proto() {
	[ -n "$1" ] || return 0
	l4proto="meta l4proto $(nft_element_list "$1")"
}

rule_nfproto() {
	[ -n "$1" ] || return 0
	nfproto="meta nfproto $(nft_element_list "$1")"
}

rule_oifname() {
	[ -n "$1" ] || return 0
	oifname="oifname $(nft_interface_list "$1")"
}

rule_iifname() {
	[ -n "$1" ] || return 0
	iifname="iifname $(nft_interface_list "$1")"
}

rule_zone() {
	local direction="$1" zone="$2"
	local interfaces

	[ -n "$zone" ] || return 0

	interfaces="$(fw_zone_interfaces "$zone")" || {
		log warning "Rule contains an invalid ${direction} zone"
		return 1
	}

	case "$direction" in
	src) rule_iifname "$interfaces" ;;
	dest) rule_oifname "$interfaces" ;;
	*)
		log err "Invalid direction for zone function"
		return 1
		;;
	esac
}

rule_port() {
	local direction="$1" ports="$2" protocol="$3"
	local port port_negate rule xport

	case "$direction" in
	src) xport="sport" ;;
	dest) xport="dport" ;;
	*)
		log err "Invalid direction for port function"
		return 1
		;;
	esac

	[ -n "$ports" ] || return 0

	check_port_proto "$protocol" || {
		log warning "Rules cannot combine a ${direction}_port with protocols other than 'tcp' or 'udp'"
		return 1
	}

	parse_rule_ports "$ports" || {
		log warning "Rule contains an invalid ${direction}_port"
		return 1
	}

	[ -n "$port" ] && rule="th $xport $(nft_element_list "$port")"
	[ -n "$port_negate" ] && rule="$rule th $xport != $(nft_element_list "$port_negate")"

	eval "$xport"='$rule'
	return 0
}

rule_addr() {
	local direction="$1" addresses="$2" family="$3" 
	local rule rule6 xaddr
	local ipv4 ipv6 ipset
	local ipv4_negate ipv6_negate ipset_negate

	case "$direction" in
	src) xaddr="saddr" ;;
	dest) xaddr="daddr" ;;
	*)
		log err "Invalid direction for addr function"
		return 1
		;;
	esac

	[ -n "$addresses" ] || return 0

	if [ -n "$family" ] && ! check_family "$family"; then
		log warning "Rule contains an invalid family"
		return 1
	fi

	parse_rule_ips "$addresses" || {
		log warning "Rule contains an invalid ${direction}_ip"
		return 1
	}
	if [ -n "$ipset$ipset_negate" ] && [ -n "$ipv4$ipv6$ipv4_negate$ipv6_negate" ]; then
		log warning "Rules must not mix IP addresses and sets in the ${direction}_ip option"
		return 1
	fi
	if [ -n "$ipv4$ipv4_negate" ] && [ "$family" = "ipv6" ]; then
		log warning "Rules cannot combine an ipv4 ${direction}_ip with the 'ipv6' family option"
		return 1
	fi
	if [ -n "$ipv6$ipv6_negate" ] && [ "$family" = "ipv4" ]; then
		log warning "Rules cannot combine an ipv6 ${direction}_ip with the 'ipv4' family option"
		return 1
	fi
	if [ "$(echo "$ipset" | wc -w)" -gt 1 ] || [ "$(echo "$ipset_negate" | wc -w)" -gt 1 ]; then
		log warning "Rules must not contain more than one set for the ${direction}_ip option"
		return 1
	fi

	[ -n "$ipv4" ] && rule="ip $xaddr $(nft_element_list "$ipv4")"
	[ -n "$ipv4_negate" ] && rule="$rule ip $xaddr != $(nft_element_list "$ipv4_negate")"

	[ -n "$ipv6" ] && rule6="ip6 $xaddr $(nft_element_list "$ipv6")"
	[ -n "$ipv6_negate" ] && rule6="$rule6 ip6 $xaddr != $(nft_element_list "$ipv6_negate")"

	[ -n "$ipset$ipset_negate" ] && case "$family" in
	ipv4)
		[ -n "$ipset" ] && rule="$rule ip $xaddr $ipset"
		[ -n "$ipset_negate" ] && rule="$rule ip $xaddr != $ipset_negate"
		;;
	ipv6)
		[ -n "$ipset" ] && rule6="$rule6 ip6 $xaddr $ipset"
		[ -n "$ipset_negate" ] && rule6="$rule6 ip6 $xaddr != $ipset_negate"
		;;
	*)
		log warning "Rules must contain the family option when a set is present in the ${direction}_ip option"
		return 1
		;;
	esac

	eval "$xaddr"='$rule'
	eval "$xaddr"6='$rule6'
	return 0
}

rule_device() {
	local device="$1" direction="$2"
	[ -n "$device" ] || return 0

	[ -n "$direction" ] || {
		log warning "Rules must use the options 'device' and 'direction' in conjunction"
		return 1
	}

	case "$direction" in
	in) rule_iifname "$device" ;;
	out) rule_oifname "$device" ;;
	*)
		log warning "The rule option 'direction' must contain either 'in' or 'out'"
		return 1
		;;
	esac
}

rule_verdict() {
	local class="$1"

	[ -n "$class" ] || {
		log warning "Rule is missing the DSCP 'class' option"
		return 1
	}
	class="$(dscp_class "$class")" || {
		log warning "Rule option 'class' contains an invalid DSCP value"
		return 1
	}
	verdict="goto ct_set_${class}"
}

create_user_rule() {
	local section="$1"
	local enabled family proto direction device dest dest_ip dest_port src src_ip src_port counter class name
	local nfproto l4proto oifname daddr daddr6 dport iifname saddr saddr6 sport verdict
	local error=0

	config_get_bool enabled "$section" enabled 1
	[ "$enabled" = 1 ] || return 0

	config_get family "$section" family
	config_get proto "$section" proto
	config_get device "$section" device # L3 physical interface
	config_get direction "$section" direction
	config_get dest "$section" dest
	config_get dest_ip "$section" dest_ip
	config_get dest_port "$section" dest_port
	config_get src "$section" src
	config_get src_ip "$section" src_ip
	config_get src_port "$section" src_port
	config_get_bool counter "$section" counter
	config_get class "$section" class
	config_get name "$section" name

	rule_nfproto "$family" || error=1
	rule_l4proto "$proto" || error=1
	rule_zone dest "$dest" || error=1
	rule_addr dest "$dest_ip" "$family" || error=1
	rule_port dest "$dest_port" "$proto" || error=1
	rule_zone src "$src" || error=1
	rule_addr src "$src_ip" "$family" || error=1
	rule_port src "$src_port" "$proto" || error=1
	rule_device "$device" "$direction" || error=1
	rule_verdict "$class" || error=1
	[ "$error" = 0 ] || return 1

	[ -z "$daddr$saddr$daddr6$saddr6" ] && {
		post_include "insert rule inet dscpclassify rule_classify $nfproto $l4proto $oifname $dport $iifname $sport ${counter:+counter} $verdict ${name:+comment \"$name\"}"
		return 0
	}
	[ -n "$daddr$saddr" ] && {
		post_include "insert rule inet dscpclassify rule_classify $nfproto $l4proto $oifname $daddr $dport $iifname $saddr $sport ${counter:+counter} $verdict ${name:+comment \"$name\"}"
	}
	[ -n "$daddr6$saddr6" ] && {
		post_include "insert rule inet dscpclassify rule_classify $nfproto $l4proto $oifname $daddr6 $dport $iifname $saddr6 $sport ${counter:+counter} $verdict ${name:+comment \"$name\"}"
	}
	return 0
}

destroy_client_class_adoption_rules() {
	post_include "destroy chain inet dscpclassify client_classify"
}

create_client_class_adoption_rules() {
	local enabled=1
	local exclude_class_defaults="cs6 cs7"
	local exclude_class src_ip
	local saddr saddr6

	config_get_bool enabled "$client_class_adoption_config" enabled "$enabled"
	[ "$enabled" = 1 ] || {
		destroy_client_class_adoption_rules
		return 0
	}

	config_get exclude_class "$client_class_adoption_config" exclude_class "$exclude_class_defaults"
	for class in $exclude_class; do
		class="$(dscp_class "$class")" || {
			log err "The client_class_adoption config option 'exclude_class' contains an invalid DSCP class"
			return 1
		}
		case "$class" in
		le) class=lephb ;;  # RFC-8622
		cs0) continue ;;
		esac
		exclude_class="${exclude_class:+$exclude_class }\$${class}"
	done

	# Create exluded classes list, cs0 is always excluded
	exclude_class="$(nft_element_list "cs0 $exclude_class")"

	config_get src_ip "$section" src_ip
	rule_addr src "$src_ip" || {
		log err "The client_class_adoption config is invalid"
		return 1
	}

	# Create client class adoption rules
	post_include "add rule inet dscpclassify client_classify $saddr ip dscp != $exclude_class ip dscp vmap @dscp_ct"
	post_include "add rule inet dscpclassify client_classify $saddr6 ip6 dscp != $exclude_class ip6 dscp vmap @dscp_ct"

	# Create jump from input and postrouting chains
	post_include "add rule inet dscpclassify input ct mark & \$ct_dynamic != 0 ct direction original iifname != \$wan jump client_classify"
	post_include "add rule inet dscpclassify postrouting ct mark & \$ct_dynamic != 0 ct direction original iifname != \$wan jump client_classify"
}

destroy_dynamic_classify_rules() {
	post_include "destroy chain inet dscpclassify dynamic_classify"
	post_include "destroy chain inet dscpclassify dynamic_classify_reply"
	post_include "destroy chain inet dscpclassify established_connection"
}

create_dynamic_classify_rules() {
	local bulk_client_detection=1
	local high_throughput_service_detection=1

	config_get_bool bulk_client_detection "$bulk_client_detection_config" enabled "$bulk_client_detection"
	config_get_bool high_throughput_service_detection "$high_throughput_service_detection_config" enabled "$high_throughput_service_detection"
	if [ "$bulk_client_detection" != 1 ] && [ "$high_throughput_service_detection" != 1 ]; then
		destroy_dynamic_classify_rules
		return 0
	fi

	post_include "add rule inet dscpclassify input ct mark & (\$ct_dynamic | \$ct_dscp) == \$ct_dynamic jump dynamic_classify"
	post_include "add rule inet dscpclassify postrouting ct mark & (\$ct_dynamic | \$ct_dscp) == \$ct_dynamic jump dynamic_classify"
}

destroy_bulk_client_rules() {
	post_include "destroy chain inet dscpclassify bulk_client"
	post_include "destroy chain inet dscpclassify bulk_client_reply"

	check_set_exists bulk_clients && post_include "destroy set inet dscpclassify bulk_clients"
	check_set_exists bulk_clients6 && post_include "destroy set inet dscpclassify bulk_clients6"
}

create_bulk_client_rules() {
	local class="$class_low_effort"
	local enabled=1
	local min_bytes=10000
	local min_connections=10

	config_get_bool enabled "$bulk_client_detection_config" enabled "$enabled"
	[ "$enabled" = 1 ] || {
		destroy_bulk_client_rules
		return 0
	}

	config_get min_bytes "$bulk_client_detection_config" min_bytes "$min_bytes"
	if ! check_uint "$min_bytes" || [ "$min_bytes" = 0 ]; then
		log err "bulk_client_detection config option 'min_bytes' contains an invalid value"
		return 1
	fi
	config_get min_connections "$bulk_client_detection_config" min_connections "$min_connections"
	if ! check_uint "$min_connections" || [ "$min_connections" -lt 2 ]; then
		log err "bulk_client_detection config option 'min_connections' contains an invalid value"
		return 1
	fi
	config_get class "$bulk_client_detection_config" class "$class"
	class="$(dscp_class "$class")" || {
		log err "bulk_client_detection config option 'class' contains an invalid DSCP class"
		return 1
	}

	case "$class" in
	le) class=lephb ;;  # RFC-8622
	cs0)
		destroy_bulk_client_rules
		log warning "Disabling threaded client detection as its configured class CS0/DF/BE is the default packet class"
		return 0
		;;
	esac

	# Create sets for matching threaded clients
	check_set_exists bulk_clients || post_include "add set inet dscpclassify bulk_clients { type ipv4_addr . inet_service . inet_proto; flags timeout; }"
	check_set_exists bulk_clients6 || post_include "add set inet dscpclassify bulk_clients6 { type ipv6_addr . inet_service . inet_proto; flags timeout; }"

	# Create threaded client detection rules
	post_include "add rule inet dscpclassify established_connection meter bulk_client_detect { ip daddr . th dport . meta l4proto timeout 5s limit rate over $((min_connections - 1))/minute } add @bulk_clients { ip daddr . th dport . meta l4proto timeout 30s }"
	post_include "add rule inet dscpclassify established_connection meter bulk_client_detect6 { ip6 daddr . th dport . meta l4proto timeout 5s limit rate over $((min_connections - 1))/minute } add @bulk_clients6 { ip6 daddr . th dport . meta l4proto timeout 30s }"

	# Create threaded client classification rule chains
	post_include "add chain inet dscpclassify bulk_client"
	post_include "add rule inet dscpclassify bulk_client meter bulk_client_orig_classify { ip saddr . th sport . meta l4proto timeout 5m limit rate over $((min_bytes - 1)) bytes/hour } update @bulk_clients { ip saddr . th sport . meta l4proto timeout 5m } ct mark set ct mark | \$${class} return"
	post_include "add rule inet dscpclassify bulk_client meter bulk_client_orig_classify6 { ip6 saddr . th sport . meta l4proto timeout 5m limit rate over $((min_bytes - 1)) bytes/hour } update @bulk_clients6 { ip6 saddr . th sport . meta l4proto timeout 5m } ct mark set ct mark | \$${class} return"

	post_include "add chain inet dscpclassify bulk_client_reply"
	post_include "add rule inet dscpclassify bulk_client_reply meter bulk_client_reply_classify { ip daddr . th dport . meta l4proto timeout 5m limit rate over $((min_bytes - 1)) bytes/hour } update @bulk_clients { ip daddr . th dport . meta l4proto timeout 5m } ct mark set ct mark | \$${class} return"
	post_include "add rule inet dscpclassify bulk_client_reply meter bulk_client_reply_classify6 { ip6 daddr . th dport . meta l4proto timeout 5m limit rate over $((min_bytes - 1)) bytes/hour } update @bulk_clients6 { ip6 daddr . th dport . meta l4proto timeout 5m } ct mark set ct mark | \$${class} return"

	# Create jumps from dynamic_classify chain
	post_include "add rule inet dscpclassify dynamic_classify ip saddr . th sport . meta l4proto @bulk_clients goto bulk_client"
	post_include "add rule inet dscpclassify dynamic_classify ip6 saddr . th sport . meta l4proto @bulk_clients6 goto bulk_client"

	post_include "add rule inet dscpclassify dynamic_classify_reply ip daddr . th dport . meta l4proto @bulk_clients goto bulk_client_reply"
	post_include "add rule inet dscpclassify dynamic_classify_reply ip6 daddr . th dport . meta l4proto @bulk_clients6 goto bulk_client_reply"
}

destroy_high_throughput_service_rules() {
	post_include "destroy chain inet dscpclassify high_throughput_service"
	post_include "destroy chain inet dscpclassify high_throughput_service_reply"

	check_set_exists high_throughput_services && post_include "destroy set inet dscpclassify high_throughput_services"
	check_set_exists high_throughput_services6 && post_include "destroy set inet dscpclassify high_throughput_services6"
}

create_high_throughput_service_rules() {
	local class="$class_high_throughput"
	local enabled=1
	local min_bytes=1000000
	local min_connections=3

	config_get_bool enabled "$high_throughput_service_detection_config" enabled "$enabled"
	[ "$enabled" = 1 ] || {
		destroy_high_throughput_service_rules
		return 0
	}

	config_get min_bytes "$high_throughput_service_detection_config" min_bytes "$min_bytes"
	if ! check_uint "$min_bytes" || [ "$min_bytes" = 0 ]; then
		log err "high_throughput_service_detection config option 'min_bytes' contains an invalid value"
		return 1
	fi
	config_get min_connections "$high_throughput_service_detection_config" min_connections "$min_connections"
	if ! check_uint "$min_connections" || [ "$min_connections" -lt 2 ]; then
		log err "high_throughput_service_detection config option 'min_connections' contains an invalid value"
		return 1
	fi
	config_get class "$high_throughput_service_detection_config" class "$class"
	class="$(dscp_class "$class")" || {
		log err "high_throughput_service_detection config option 'class' contains an invalid DSCP class"
		return 1
	}

	case "$class" in
	le) class=lephb ;;  # RFC-8622
	cs0)
		destroy_high_throughput_service_rules
		log warning "Disabling threaded service detection as its configured class CS0/DF/BE is the default packet class"
		return 0
		;;
	esac

	# Create sets for matching threaded services
	check_set_exists high_throughput_services || post_include "add set inet dscpclassify high_throughput_services { type ipv4_addr . ipv4_addr . inet_service . inet_proto; flags timeout; }"
	check_set_exists high_throughput_services6 || post_include "add set inet dscpclassify high_throughput_services6 { type ipv6_addr . ipv6_addr . inet_service . inet_proto; flags timeout; }"

	# Create threaded service detection rules
	post_include "add rule inet dscpclassify established_connection meter high_throughput_service_detect { ip daddr . ip saddr and 255.255.255.0 . th sport . meta l4proto timeout 5s limit rate over $((min_connections - 1))/minute } add @high_throughput_services { ip daddr . ip saddr and 255.255.255.0 . th sport . meta l4proto timeout 30s }"
	post_include "add rule inet dscpclassify established_connection meter high_throughput_service_detect6 { ip6 daddr . ip6 saddr and ffff:ffff:ffff:: . th sport . meta l4proto timeout 5s limit rate over $((min_connections - 1))/minute } add @high_throughput_services6 { ip6 daddr . ip6 saddr and ffff:ffff:ffff:: . th sport . meta l4proto timeout 30s }"

	# Create threaded service classification rule chains
	post_include "add chain inet dscpclassify high_throughput_service"
	post_include "add rule inet dscpclassify high_throughput_service ct original bytes < $min_bytes return"
	post_include "add rule inet dscpclassify high_throughput_service update @high_throughput_services { ip saddr . ip daddr and 255.255.255.0 . th dport . meta l4proto timeout 5m }"
	post_include "add rule inet dscpclassify high_throughput_service update @high_throughput_services6 { ip6 saddr . ip6 daddr and ffff:ffff:ffff:: . th dport . meta l4proto timeout 5m }"
	post_include "add rule inet dscpclassify high_throughput_service ct mark set ct mark | \$${class} return"

	post_include "add chain inet dscpclassify high_throughput_service_reply"
	post_include "add rule inet dscpclassify high_throughput_service_reply ct reply bytes < $min_bytes return"
	post_include "add rule inet dscpclassify high_throughput_service_reply update @high_throughput_services { ip daddr . ip saddr and 255.255.255.0 . th sport . meta l4proto timeout 5m }"
	post_include "add rule inet dscpclassify high_throughput_service_reply update @high_throughput_services6 { ip6 daddr . ip6 saddr and ffff:ffff:ffff:: . th sport . meta l4proto timeout 5m }"
	post_include "add rule inet dscpclassify high_throughput_service_reply ct mark set ct mark | \$${class} return"

	# Create jumps from dynamic_classify chain
	post_include "add rule inet dscpclassify dynamic_classify ip saddr . ip daddr and 255.255.255.0 . th dport . meta l4proto @high_throughput_services goto high_throughput_service"
	post_include "add rule inet dscpclassify dynamic_classify ip6 saddr . ip6 daddr and ffff:ffff:ffff:: . th dport . meta l4proto @high_throughput_services6 goto high_throughput_service"

	post_include "add rule inet dscpclassify dynamic_classify_reply ip daddr . ip saddr and 255.255.255.0 . th sport . meta l4proto @high_throughput_services goto high_throughput_service_reply"
	post_include "add rule inet dscpclassify dynamic_classify_reply ip6 daddr . ip6 saddr and ffff:ffff:ffff:: . th sport . meta l4proto @high_throughput_services6 goto high_throughput_service_reply"
}

create_dscp_mark_rule() {
	local wmm_mark_lan=1

	config_get_bool wmm_mark_lan "$service_config" wmm_mark_lan "$wmm_mark_lan"
	[ "$wmm_mark_lan" = 1 ] && post_include "add rule inet dscpclassify postrouting oifname \$lan ct mark & \$ct_dscp vmap @ct_wmm"
	
	post_include "add rule inet dscpclassify postrouting ct mark & \$ct_dscp vmap @ct_dscp"
}

create_flush_actions() {
	for chain in $(nft -j list chains | jsonfilter -e '@.nftables[@.chain.table="dscpclassify"].chain.name'); do
		pre_include "flush chain inet dscpclassify ${chain}"
	done
	for map in $(nft -j list maps | jsonfilter -e '@.nftables[@.map.table="dscpclassify"].map.name'); do
		pre_include "flush map inet dscpclassify ${map}"
	done

	# Destroy orphaned meter sets	
	check_set_exists bulk_client_detect && pre_include "destroy set inet dscpclassify bulk_client_detect"
	check_set_exists bulk_client_detect6 && pre_include "destroy set inet dscpclassify bulk_client_detect6"
	check_set_exists bulk_client_orig_classify && pre_include "destroy set inet dscpclassify bulk_client_orig_classify"
	check_set_exists bulk_client_orig_classify6 && pre_include "destroy set inet dscpclassify bulk_client_orig_classify6"
	check_set_exists bulk_client_reply_classify && pre_include "destroy set inet dscpclassify bulk_client_reply_classify"
	check_set_exists bulk_client_reply_classify6 && pre_include "destroy set inet dscpclassify bulk_client_reply_classify6"
	check_set_exists high_throughput_service_detect && pre_include "destroy set inet dscpclassify high_throughput_service_detect"
	check_set_exists high_throughput_service_detect6 && pre_include "destroy set inet dscpclassify high_throughput_service_detect6"
}

create_pre_include() {
	rm -f "$PRE_INCLUDE"

	pre_include "define lan = $(nft_interface_list "$lan")"
	pre_include "define wan = $(nft_interface_list "$wan")"

	pre_include "add table inet dscpclassify"
	[ "$action" = "reload" ] && create_flush_actions 

	pre_include "include \"${VERDICTS}\""
	pre_include "include \"${MAPS}\""
}

create_post_include() {
	rm -f "$POST_INCLUDE"

	config_foreach create_user_set set   # deprecating in favour of 'ipset' section name for consistency with fw4
	config_foreach create_user_set ipset # section name consistent with fw4
	config_foreach_reverse create_user_rule rule

	create_client_class_adoption_rules || return 1
	create_dynamic_classify_rules || return 1
	create_bulk_client_rules || return 1
	create_high_throughput_service_rules || return 1

	create_dscp_mark_rule || return 1
}

get_zones() {
	local interfaces lan_zones wan_zones

	config_get lan "$service_config" lan_device # L3 physical interface
	config_get lan_zones "$service_config" lan_zone "lan"
	for zone in $lan_zones; do
		interfaces="$(fw_zone_interfaces "$zone")" && lan="${lan:+$lan }${interfaces}"
	done
	[ -n "$lan" ] || return 1

	config_get wan "$service_config" wan_device # L3 physical interface
	config_get wan_zones "$service_config" wan_zone "wan"
	for zone in $wan_zones; do
		interfaces="$(fw_zone_interfaces "$zone")" && wan="${wan:+$wan }${interfaces}"
	done
	[ -n "$wan" ] || return 1
}

migrate_config() {
    local changed=0

    # Ensure a section exists, create it if missing
    ensure_section_exists() {
        local type="$1"
        uci get dscpclassify.@${type}[0] &>/dev/null || {
            uci add dscpclassify "$type" >/dev/null
            changed=1
        }
    }

    # Move an option from one section to another
    move_unique_section_option() {
        local from_type="$1" from_opt="$2" to_type="$3" to_opt="$4"
        if uci get dscpclassify.@${from_type}[0].${from_opt} &>/dev/null; then
            ensure_section_exists "$to_type"
            uci set dscpclassify.@${to_type}[0].${to_opt}="$(uci get dscpclassify.@${from_type}[0].${from_opt})"
            uci delete dscpclassify.@${from_type}[0].${from_opt}
            changed=1
        fi
    }

	# Rename a section type
	rename_section_type() {
        local from_type="$1" to_type="$2"
    	for idx in $(uci show dscpclassify | grep "=${from_type}$" | cut -d'[' -f2 | cut -d']' -f1); do
    	    uci rename "dscpclassify.@${from_type}[$idx]=${to_type}"
    	    changed=1
    	done
    }

    # Migrate global options to new section types
    if uci get dscpclassify.@global[0] &>/dev/null; then
		# Options for the 'service' section
		move_unique_section_option global lan_device service lan_device
		move_unique_section_option global lan_zone service lan_zone
		move_unique_section_option global wan_device service wan_device
		move_unique_section_option global wan_zone service wan_zone
		move_unique_section_option global debug service debug
		move_unique_section_option global class_low_effort service class_low_effort
		move_unique_section_option global class_high_throughput service class_high_throughput
        move_unique_section_option global wmm service wmm_mark_lan

		# Options for the 'client_class_adoption' section
    	move_unique_section_option global client_hints client_class_adoption enabled

		# Options for the 'bulk_client_detection' section
		move_unique_section_option global threaded_client_detection bulk_client_detection enabled
    	move_unique_section_option global threaded_client_min_bytes bulk_client_detection min_bytes
    	move_unique_section_option global threaded_client_min_connections bulk_client_detection min_connections

		# Options for the 'high_throughput_service_detection' section
		move_unique_section_option global threaded_service_detection high_throughput_service_detection enabled
    	move_unique_section_option global threaded_service_min_bytes high_throughput_service_detection min_bytes
    	move_unique_section_option global threaded_service_min_connections high_throughput_service_detection min_connections

        uci delete dscpclassify.@global[0]
        changed=1
    fi

    # Rename all 'set' type sections to 'ipset'
	rename_section_type set ipset

    [ "$changed" = 1 ] && {
	uci commit dscpclassify
	log notice "Service config migrated"
    }
    return 0
}

setup() {
	local lan wan
	local service_config
	local client_class_adoption_config
	local bulk_client_detection_config
	local high_throughput_service_detection_config

	local class_low_effort="le"
	local class_high_throughput="af13"

	check_minimum_kernel_release 5.13 || {
		log info "Falling back to CS1 for default Low Effort class due to Kernel version < 5.13"
		class_low_effort="cs1"
	}

	cleanup_setup
	migrate_config
	config_load dscpclassify || {
		log err "Failed to load config file"
		return 1
	}

	config_get_exclusive_section service_config service
	config_get_exclusive_section client_class_adoption_config client_class_adoption
	config_get_exclusive_section bulk_client_detection_config bulk_client_detection
	config_get_exclusive_section high_throughput_service_detection_config high_throughput_service_detection

	config_get_bool debug "$service_config" debug "$DEBUG"
	config_get class_low_effort "$service_config" class_low_effort "$class_low_effort"
	config_get class_high_throughput  "$service_config" class_high_throughput "$class_high_throughput"

	get_zones || {
		log info "Deferring ${action} because lan/wan firewall zones are unavailable"
		return 0
	}

	[ "$action" = "start" ] && destroy_table

	mkdir -p "$INCLUDES_PATH" || {
		log err "Failed to create path: ${INCLUDES_PATH}"
		return 1
	}
	create_pre_include || {
		log err "Failed to create pre-include rules"
		return 1
	}
	create_post_include || {
		log err "Failed to create post-include rules"
		return 1
	}

	nft_result="$(nft -f "$MAIN" 2>&1)" || {
		log err "Failed to load main.nft with status: $?"
		return 1
	}
	return 0
}

setup_failed() {
	log warning "Service ${action} failed"
	[ "${debug:-$DEBUG}" = 1 ] && create_debug_file
	destroy_table
	delete_includes
}

start_service() {
	setup || {
		setup_failed
		return 1
	}
	cleanup_setup
	log notice "Service ${action}ed"
	return 0
}

reload_service() {
	/etc/init.d/dscpclassify status &>/dev/null || {
		echo "The dscpclassify service is not loaded"
		return 1
	}
	start_service
}

stop_service() {
	cleanup_service
	log notice "Service stopped"
	return 0
}
